apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ include "app.fullname" . }}
spec:
  selector:
    app: {{ .Values.deployment.labels.app }}        
  {{- range .Values.service.ports }}
  ports:
  - port: {{ .servicePort }}
    targetPort: {{ .containerPort }}
    {{- if eq .type "NodePort" "LoadBalancer" }}
    nodePort: {{ .nodePort }}
    {{- end }}
  type: {{ .type }}
  {{- end }}
